openapi: 3.0.0
paths:
  /v1/cats:
    get:
      operationId: CatController_listCats
      parameters: []
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CatResponse'
        '400':
          description: bad request
        '403':
          description: forbidden
        '500':
          description: internal server error
      tags: &ref_0
        - cats
    post:
      operationId: CatController_createCats
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CatRequest'
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CatResponse'
      tags: *ref_0
    put:
      operationId: CatController_updateCats
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CatRequest'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CatResponse'
      tags: *ref_0
  /v1/cats/{id}:
    get:
      operationId: CatController_getCatById
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CatResponse'
      tags: *ref_0
info:
  title: Cats example
  description: ''
  version: '1.0'
  contact: {}
tags: []
servers:
  - url: http://localhost:3000
  - url: https://localhost:3000
components:
  schemas:
    CatResponse:
      type: object
      properties:
        name:
          type: string
        age:
          type: number
        birthday:
          type: string
      required:
        - name
        - age
        - birthday
    CatRequest:
      type: object
      properties: {}
