name: Node.js CI

on:
  push:
    branches: [ "feature/*", "fix/*", "renovate/*", "main" ]
    paths:
      - "aws-serverless/**"
      - ".github/workflows/aws-serverless-node.js.yml"
  pull_request:
    types: [opened, reopened]
    paths:
      - "aws-serverless/**"
      - ".github/workflows/aws-serverless-node.js.yml"

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './aws-serverless'

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - run: npm ci
    - run: npm run build --if-present
    - uses: ArtiomTr/jest-coverage-report-action@v2
      id: coverage
      with:
        working-directory: 'aws-serverless'
        output: report-markdown
        test-script: npm run test:coverage
    - uses: marocchino/sticky-pull-request-comment@v2
      with:
        number: ${{ steps.finder.outputs.pr }}
        message: ${{ steps.coverage.outputs.report }}

