name: Qodana Code Quality CI
on:
  push:
    branches: [ "feature/*", "fix/*", "renovate/*", "main" ]
  pull_request:
    types: [opened, reopened]
    branches: [ "feature/*", "fix/*", "renovate/*", "main" ]

jobs:
  qodana:
    runs-on: ubuntu-latest
    using: 'node16'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2022.2.2