name: Qodana Code Quality CI
on:
  push:
    branches: [ "feature/*", "fix/*", "renovate/*", "main" ]
    paths:
      - "express-docker/**"
      - ".github/workflow/foo.yaml"
  pull_request:
    types: [opened, reopened]
    paths:
      - "express-docker/**"
      - ".github/workflow/foo.yaml"

jobs:
  qodana:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./express-docker
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2022.2.2