name: Qodana Code Quality CI
on:
  push:
    branches: [ "feature/*", "fix/*", "renovate/*", "main" ]
  pull_request:
    branches: [ "feature/*", "fix/*", "renovate/*", "main" ]
    types: [opened, reopened]

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.3.2
#     - uses: github/codeql-action/upload-sarif@v2
#       with:
#         sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
#     - name: Deploy to GitHub Pages
#       uses: peaceiris/actions-gh-pages@v3
#       with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}
#         publish_dir: ${{ runner.temp }}/qodana/results/report
#         destination_dir: ./
