# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "feature/*", "fix/*", "renovate/*", "main" ]
    paths:
      - "fastify-docker/**"
      - ".github/workflows/fastify-docker-node.js.yml"
  pull_request:
    types: [opened, reopened]
    paths:
      - "fastify-docker/**"
      - ".github/workflows/fastify-docker-node.js.yml"

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './fastify-docker'

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - run: npm ci
    - run: npm run build --if-present
    - uses: ArtiomTr/jest-coverage-report-action@v2
      id: coverage
      with:
        working-directory: 'fastify-docker'
        output: report-markdown
        test-script: npm run test:coverage
    - uses: marocchino/sticky-pull-request-comment@v2
      with:
        number: ${{ steps.finder.outputs.pr }}
        message: ${{ steps.coverage.outputs.report }}